# Generated by Django 3.0.7 on 2020-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='big_image',
            field=models.ImageField(default=None, upload_to='stored/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(default=None, upload_to='stored/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='low_image_1',
            field=models.ImageField(default=None, upload_to='stored/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='low_image_2',
            field=models.ImageField(default=None, upload_to='stored/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
