# Generated by Django 3.0.7 on 2020-06-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200623_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='big_image',
            field=models.ImageField(default=None, upload_to='stored/projects/big'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(default=None, upload_to='stored/projects/logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='low_image_1',
            field=models.ImageField(default=None, upload_to='stored/projects/low'),
        ),
        migrations.AlterField(
            model_name='project',
            name='low_image_2',
            field=models.ImageField(default=None, upload_to='stored/projects/low'),
        ),
    ]
