# Generated by Django 3.0.8 on 2020-07-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='big_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='low_image_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='low_image_2',
        ),
    ]
